# Generated by Django 5.2 on 2025-04-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_useractivity_remove_post_platform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['-timestamp'], 'verbose_name': 'User Activity', 'verbose_name_plural': 'User Activities'},
        ),
    ]
